### ISSUE TITLE
[EAT-20] nullpointerException cell 발생 및 유령 cell이 생성

### ISSUE THREAD

**Issue by ywjywj** [have-a-meal/have-a-meal-server#13]
### 상위 이슈
- [excel to java](https://jaewoong.atlassian.net/browse/EAT-20)
### 하위 이슈
- [EAT-83](https://jaewoong.atlassian.net/browse/EAT-83)
### 이슈 내용
- 이미지
  ![유령 cell 및 nullpointerexception](https://github.com/have-a-meal/have-a-meal-server/assets/99004684/319b6c6d-40d6-4b50-bfa5-6f28fe3cb922)
- 설명
   - 엑셀 데이터 java로 변환하는 과정에서 nullpointerException 발생
   - 아무 값을 안가지는 셀이 무작위로 출력

[EAT-83]: https://jaewoong.atlassian.net/browse/EAT-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jaewoong-gwon** [comment]
엑셀에서 내용이 없더라도 클릭이나 작업을 했다고 판단되는 셀도 읽는거 같은데..

**Comment by ywjywj** [comment]
![귀신 열 해결](https://github.com/have-a-meal/have-a-meal-server/assets/99004684/6a3f9c0f-eeca-436f-bcb5-fa5f88702660)
- 원인
   - 식단표 엑셀 주변의 셀에 아무것도 없어도 작업한 흔적이 있으면 작업했다고 인식함.
- 해결
   - 주변 셀들을 삭제하는 작업이 필요함.

**Comment by ywjywj** [comment]
회의를 통해서 식단표의 양식을 고정시키고 그 크기만큼만 데이터를 가져오는 방법으로 진행하기로 하였음.
아쉬운 점으로는 엑셀 파일에 종속적이라는 점에서 아쉬움이 큼.
