### ISSUE TITLE
[EAT-80] 유틸성 클래스 public 생성자 이슈

### ISSUE THREAD

**Issue by jaewoong-gwon** [have-a-meal/have-a-meal-server#14]
### 상위 이슈
- [UUID](https://jaewoong.atlassian.net/browse/EAT-47) 
### 하위이슈
- [EAT-80](https://jaewoong.atlassian.net/browse/EAT-80) 
### 이슈 내용
- 이미지
   ![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/eb5da9c1-9f92-45d1-bfbe-648ca1d6f51f)
- 설명
   - static 멤버들로 구성된 클래스(Util 성 객체)는 인스턴스화 되지 않아야하기 때문에  non-public 한 생성자를 하나 명시적으로 정의해야 한다
- 참고사항
   -   [JAVA:S1118](https://rules.sonarsource.com/java/RSPEC-1118/)

[EAT-80]: https://jaewoong.atlassian.net/browse/EAT-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jaewoong-gwon** [comment]
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/0fe8ff20-cd21-478c-b8b6-2a945a4d74db)
- private 생성자를 명시하여 해결하였습니다

**Comment by ywjywj** [comment]
좋은 정보 였습니다!
