### ISSUE TITLE
[EAT-86] Mybatis 동작 과정에서 UnsupportedOperationException 발생

### ISSUE THREAD

**Issue by jaewoong-gwon** [have-a-meal/have-a-meal-server#18]
### 상위 이슈
- [Error](https://jaewoong.atlassian.net/browse/EAT-74)
### 이슈 링크
- [EAT-86](https://jaewoong.atlassian.net/browse/EAT-86)
### 이슈 내용
- 이미지
  ![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/85f48075-849d-4aa9-843d-a2b72cc684d6)
  ![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/35a82182-3d87-4ff8-8ed2-60ca5899f3a4)
  ![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/1d6a3ca4-2c88-45a8-b286-b1fa2fbf7fc9)
  ![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/38104f0d-ca55-4b46-bc19-57d2b7fbafc4)
  ![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/6227c2d8-97ff-451a-9d5a-ef77634d0d85)
- 설명
   - mapper.xml 에 적힌 쿼리를 실행하는 도중 제목의 익셉션이 발생함
   - 해당 쿼리는 Member Entity 를 매개변수로 받아, PaymentWithCourseIncludeDetail Entity 로 결과를 반환함
   - 로그를 찍어본 결과, 쿼리는 정상적으로 처리된것으로 확인
   - 데이터를 매핑하는 과정에서 익셉션이 발생한것으로 추정함
[EAT-86]: https://jaewoong.atlassian.net/browse/EAT-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jaewoong-gwon** [comment]
- resultMap 태그의 type 속성 값을 List 대신 정확한 Entity 타입으로 명시하여 익셉션 해결
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/cff9211e-f434-4fdc-abdf-e4bedd5d1762)
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/bd993116-ca4e-4312-a9be-6e9252750311)

**Comment by wjdwnsdnjs13** [comment]
List 생성 시 PaymentWithCourseIncludeDetail 를 제네릭에 사용하는 부분에서 문제가 있지 않은 가 싶은 생각도 듭니다.

**Comment by wjdwnsdnjs13** [comment]
아...
resultMap에서 type에 List라고 작성한 것이 문제가 아닐까 생각됩니다 ㅋㅋㅋㅋ
java.util.List
