### ISSUE TITLE
[EAT-87] Mybatis resultmap 결과 비정상 매핑

### ISSUE THREAD

**Issue by jaewoong-gwon** [have-a-meal/have-a-meal-server#19]
### 상위 이슈
- [Error](https://jaewoong.atlassian.net/browse/EAT-74)
### 이슈 링크
- [EAT-87](https://jaewoong.atlassian.net/browse/EAT-87)
### 이슈 내용
- 이미지  
#### 1. resultmap
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/d5234c90-3f74-4300-a6fa-5d11d83cca78)
#### 2. select 
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/686d6694-9235-4df7-a4d2-504e28372bc6)
#### 3.  쿼리 로그
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/553b2100-b6a6-438f-b97a-abda846f8907)
#### 4.  결과 로그
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/56aad69a-29a5-45bb-b649-cd89002bb3fd)
#### 5. 데이터 로그
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/54641cd1-f4b0-4a19-9b12-97b0ab0eb6ad)
--- 
- 설명
   - 쿼리 실행 결과 **3개의 데이터**가 추출되었지만 결과 매핑에서 **2개의 데이터**만 매핑됨
   - 로그상 결과가 정확하게 나온것을 보면, resultmap 에 명시한 **결과 매핑 시 문제**가 있는것으로 추측
   - **association 태그** 사용법에 대한 학습이 필요해보임

[EAT-87]: https://jaewoong.atlassian.net/browse/EAT-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jaewoong-gwon** [comment]
### 1. TestMappingObject 객체
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/7720db1c-fad1-4ff7-8cb6-ae0d84b4b73e)
- 매핑 문제를 테스트해보기 위해 사용.
- 객체 매핑하는것이 아닌 필드 자체에 매핑을 테스트해봄.
### 2. resultmap
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/4e9facf1-7af7-4b8f-ba67-93694e7a036b)
- TestMappingObject 객체로 매핑하는 resultmap.
### 3. 매핑 결과
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/841d66a6-0117-406d-9b35-fa7b6a2e6d88)
---
### 결론
- 객체로 매핑하는것이 아닌 필드자체에 매핑을 시도함.
- id 태그를 안쓰긴 하였지만, 정상적으로 **3개의 데이터** 가 매핑된것 확인.
- asscositaion 태그를 사용하여 결과 매핑하는 과정에서 문제가 생긴것으로 추측.

**Comment by wjdwnsdnjs13** [comment]
해당 사항 push해서 테스트중인 코드 올려주세요
쿼리만 사용했을 때에는 3개의 데이터가 정상 매핑이 되네요...
제 컴퓨터에서 해보겠습니당

**Comment by jaewoong-gwon** [comment]
해뒀습니다~ 확인해주세요! 👍

**Comment by jaewoong-gwon** [comment]
### 1.  TicketQuantity 
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/fc0de203-83d2-48d7-86ef-170125eaf28f)
- count(*) 에 대한 결과 매핑에 association 을 사용하기 위해 객체로 만듬.
### 2. resultmap
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/e34bfda2-c49c-402e-8721-33239b844bbc)
- TicketQuantity 에 객체로 매핑하게 변경함.
### 3. 데이터 로그
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/a44a7835-f805-4868-a4c1-c5c77b743c61)
- 제대로 매핑되어 3개의 데이터가 나온것으로 확인
### 4. ResultSet 로그
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/1feac227-f073-4eba-ba25-ddb60b15b0e2)
- quantity 에 대해 getInt() 메서드가 2번 호출된것으로 확인
---
### 결론
- association 밖에 있던 quantity 에 대한 매핑 방법을 변경하였더니 3개의 데이터가 매핑됨.
- id 태그 없이 result 태그만 사용한것이 문제였던것으로 추측함.
- 4번 이미지 처럼, ResultSet 에 quntity 를 2번 가져온것에 대한 이유를 모르겠음.
- Mybatis 상세 동작 과정에대한 학습이 필요해 보임.

**Comment by jaewoong-gwon** [comment]
## 해결
### 이미지
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/733faf8a-f067-4d62-bce8-56682fd40e51)
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/067f6af2-679d-4d33-9074-3c1dc2e453a6)
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/6552c558-9050-4c73-ab90-cda9523dd6a1)
### 설명
- result 태그만 사용한 것이 Mybatis 에서 해당 컬럼을 기준으로 매핑을 시도했던것으로 판단.
- id 태그 사용으로 정상 매핑 되는것을 확인
