### ISSUE TITLE
[EAT-97] Dto - Entity 변환 메소드 잘못된 패턴 적용

### ISSUE THREAD

**Issue by jaewoong-gwon** [have-a-meal/have-a-meal-server#24]
### 이슈 링크
- [EAT-97](https://jaewoong.atlassian.net/browse/EAT-97)
### 이슈 내용
- 이미지
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/3140cf91-af1f-4589-a6b7-b66be88ee32a)
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/60cf8767-152a-4460-a9e8-60e11316f356)
- 설명
   - 정적 팩토리 메서드 패턴은 static method 를 통해 객체를 생성하는 패턴.
   - 해당 객체를 생성하는 메소드가 아닌 변환 메소드를 해당 패턴을 적용하여 만들었음.
   - **두 번째** 이미지의 **24번 라인** 을 보면 실제로 MemberEntity 를 Mapper 에 넘겨주지만 어떤 객체가 전달되는지 알아보기 힘듦.
- 참고사항
   - [Inpa Dev Tistory - 정적 팩토리 메서드 패턴](https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EC%83%9D%EC%84%B1%EC%9E%90-%EB%8C%80%EC%8B%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EC%9E%90)

[EAT-97]: https://jaewoong.atlassian.net/browse/EAT-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by wjdwnsdnjs13** [comment]
메소드 명에서 명확하게 보인다는 점은 이전보다 낫다고 생각합니다.
이전에 정적 메소드로 만들었던 변환 로직을 인스턴스 메소드로 변경하게되었는데, 이유가 무엇일까요?

**Comment by jaewoong-gwon** [comment]
정적 팩토리 메소드 패턴은
1. 생성자를 private 로
2. 해당 팩토리 메소드에서 생성자를 호출하여 객체를 생성
위의 과정을 통해 말씀해준것과 같은 여러 장점들이 있는 패턴으로 알고있습니다.

- 제가 사용한 메소드는 객체를 생성하는 역할을 하는것이 아닌 Entity 로의 변환으로 사용하고 있어 해당 패턴을 잘못 적용하였다고 생각합니다.
- Entity 로의 변환하는 메소드의 경우 여러 종류로 오버로딩 될 수 있고 이를 전부 static 으로 사용해야할 이유가 없다고 생각합니다.
