### ISSUE TITLE
[EAT - 119] HTTP Method 사용 범위 결정

### ISSUE THREAD

**Issue by jaewoong-gwon** [have-a-meal/have-a-meal-server#34]
### 이슈 링크
- [EAT-119](https://jaewoong.atlassian.net/browse/EAT-119)
### 이슈 내용
- 이미지
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/92a749dc-eb72-4478-879b-c9189e911328)
![image](https://github.com/have-a-meal/have-a-meal-server/assets/75228991/f4328081-5ccf-4e8e-845a-fa41c2c6c50b)
- 설명
   - 현재 Rest API 기반으로 개발을 진행 중이신데 사용하는 HTTP Method 의 사용 범위를 통일 했으면 합니다.
   - 예를 들어 **리소스 조회**하는 API 는 **GET** 으로, **리소스 생성**은 **POST**, **리소스 수정**은 **PUT or PATCH** 등으로 어떤 메소드를 사용할지, 어떤 상황에선 어떤 메소드를 쓸지 등 입니다.
   - 누구는 대부분의 요청을 POST 로 처리하고, 누구는 다양하게 사용하고 이런식으로 진행할 경우 통일성이 떨어 질 것 같아 고민되어 개발이 더 진행 되기전 얘기를 해보면 좋을 것 같습니다~
- 참고사항
    - 이미지 출처 : https://developer.mozilla.org/ko/docs/Web/HTTP/Methods 
### 결론
- 팀원 여러분의 생각을 남겨주세요!

[EAT-119]: https://jaewoong.atlassian.net/browse/EAT-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ywjywj** [comment]
엔드포인트 메소드별 어노테이션 사용을 위 이미지 용도에 맞게 사용하라는걸로 이해했는데 맞나요??

**Comment by jaewoong-gwon** [comment]
> 엔드포인트 메소드별 어노테이션 사용을 위 이미지 용도에 맞게 사용하라는걸로 이해했는데 맞나요??

이 부분은 이제 제가 생각하고 있는 부분이고 원준님은 어떻게 생각하시나요?

**Comment by geonwoo0423** [comment]
상의 후 통일하는게 좋아보입니다!

**Comment by wjdwnsdnjs13** [comment]
저도 HTTP Method에 대한 공부를 한 이후 느낀 점은 GET과 POST를 이전에는 제대로 사용하지 못 했다는 생각을 했습니다.
각 Method의 용도에 맞게
GET : 데이터 변경 없이 조회
POST : 데이터 삽입
PUT : 데이터 변경
DELETE : 데이터 삭제
정도로 사용하는 것이 어떤 가 생각합니다.

**Comment by ywjywj** [comment]
저는 HTTP Method의 주요 메소드인 GET,POST,PUT,DELETE 정도 만을 고려하고 사용하였는데 PATCH와 같이 부분적 수정에 쓰이는 Method도 사용하는 게 리뷰 할 때나 다시 볼 때 엔드 포인트 별 역할을 인지하고 읽는 느낌이라 더 좋을 거 같다는 느낌이 드네요
준원 님이 제시한 사항에서
PUT : 데이터 전체를 변경
PATCH : 데이터 일부를 변경
정도로 이 부분에 대해서 만 더 상세하게 나누는 건 어떤 가 생각합니다!

**Comment by jaewoong-gwon** [comment]
> 저도 HTTP Method에 대한 공부를 한 이후 느낀 점은 GET과 POST를 이전에는 제대로 사용하지 못 했다는 생각을 했습니다. 각 Method의 용도에 맞게 GET : 데이터 변경 없이 조회 POST : 데이터 삽입 PUT : 데이터 변경 DELETE : 데이터 삭제 정도로 사용하는 것이 어떤 가 생각합니다.

저도 같은 생각입니다. ㅋㅋ
용도에 맞게 사용하는게 좋을것 같아요!

**Comment by jaewoong-gwon** [comment]
> 저는 HTTP Method의 주요 메소드인 GET,POST,PUT,DELETE 정도 만을 고려하고 사용하였는데 PATCH와 같이 부분적 수정에 쓰이는 Method도 사용하는 게 리뷰 할 때나 다시 볼 때 엔드 포인트 별 역할을 인지하고 읽는 느낌이라 더 좋을 거 같다는 느낌이 드네요 준원 님이 제시한 사항에서 PUT : 데이터 전체를 변경 PATCH : 데이터 일부를 변경 정도로 이 부분에 대해서 만 더 상세하게 나누는 건 어떤 가 생각합니다!

말씀 하신 부분의차이도 있겠지만 멱등성 여부에 다르다고 합니다.
아래 링크 참고하시면 좋을것 같습니다! 
- 참고 사항
1. https://oen-blog.tistory.com/211  
2. https://mangkyu.tistory.com/251
3. https://imkdk.tistory.com/30
