### ISSUE TITLE
[EAT-125] 키 타입 결정

### ISSUE THREAD

**Issue by geonwoo0423** [have-a-meal/have-a-meal-server#39]
### 이슈 링크
- [EAT-125](https://jaewoong.atlassian.net/browse/EAT-125)
### 이슈 내용
- 설명
   - 현재 키 값은 임의로 만들어 둔 문자열이지만 SecureRandom을 사용하여 byte배열로 키 값을 생성할 예정임.
   - 암호화 키 값을 byte 배열로 생성 시 음수 값도 포함되어 문자열로 변환 시 동일한 길이로 유지가 안됨. 따라서 키 값을 문자열이 아닌 byte배열로 생성하여 사용하는게 좋아보임.

[EAT-125]: https://jaewoong.atlassian.net/browse/EAT-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jaewoong-gwon** [comment]
현재 암호화를 할 때 String 을 키로 사용하는데, 이것을 byte 배열로 키를 사용할 수 있다면 byte 배열 그대로 사용하는게 맞는것 같습니다.

**Comment by geonwoo0423** [comment]
> 현재 암호화를 할 때 String 을 키로 사용하는데, 이것을 byte 배열로 키를 사용할 수 있다면 byte 배열 그대로 사용하는게 맞는것 같습니다.

byte 배열을 DB에 저장할 때 문제가 발생하진 않나요?

**Comment by jaewoong-gwon** [comment]
DB 상에서 키를 저장할 타입은 바이너리이고, 키 길이에 맞게 설정되어 있어 문제될 것은 없다고 생각됩니다!
