### ISSUE TITLE
[EAT-126] MyBatis 바인딩 시 '와 "가 함께 붙는 문제

### ISSUE THREAD

**Issue by wjdwnsdnjs13** [have-a-meal/have-a-meal-server#40]
### 상위 이슈
- [EAT-46](https://jaewoong.atlassian.net/browse/EAT-46)
### 이슈 링크
- [EAT-126](https://jaewoong.atlassian.net/browse/EAT-126)
### 이슈 내용
- 이미지
  
![image](https://github.com/have-a-meal/have-a-meal-server/assets/67488973/f168a898-7cbf-4912-adbd-2cd42911f2e3)

![image](https://github.com/have-a-meal/have-a-meal-server/assets/67488973/63b7cdc2-1111-4abb-89fc-7b1df42f0841)

![image](https://github.com/have-a-meal/have-a-meal-server/assets/67488973/833155af-ae9b-42a2-a150-a90d5a524af3)

- 설명
   - 위 참고 내용과 같이 직접 resultMap으로 지정해줘도 바인딩 시 '와 "가 함께 붙어서 결과 값이 나오지 않는 문제가 발생합니다.

[EAT-46]: https://jaewoong.atlassian.net/browse/EAT-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EAT-126]: https://jaewoong.atlassian.net/browse/EAT-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by wjdwnsdnjs13** [comment]
하...
API 요청 보낼 때 파라미터 값에 "를 포함시켜서 그랬습니다.
해결했습니다...ㅠㅠ

**Comment by jaewoong-gwon** [comment]
확실히 테스트 케이스 설정이 중요한 것 같네요!
